<a href="https://colab.research.google.com/github/SudeepSRathod/YBI_ML/blob/main/Copy_of_Women_Cloth_Reviews_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Women Cloth Reviews Prediction with Multi Nomial Naive Bayes**


Naive Bayes is a probabilistic algorithm family based on Bayes’ Theorem. It’s “naive” because it presupposes feature independence, which means that the presence of one feature does not affect the presence of another (which may not be true in practice).

Multinomial Naive Bayes is a probabilistic classifier to calculate the probability distribution of text data, which makes it well-suited for data with features that represent discrete frequencies or counts of events in various natural language processing (NLP) tasks.

Multinomial Distribution
The term “multinomial” refers to the type of data distribution assumed by the model. The features in text classification are typically word counts or term frequencies. The multinomial distribution is used to estimate the likelihood of seeing a specific set of word counts in a document.

The probability mass function (PMF) of the Multinomial distribution is used to model the likelihood of observing a specific set of word counts in a document. It is given by:

P(D|c) = \frac{T_{c}!}{\prod_{i=1}^{V}(x_{i}!)}\prod_{i=1}^{V}\left ( \frac{\theta_{c,i }^{x_i}}{x_i !} \right )   

# **Objective**

 The objective of this project is to build a machine learning model that can predict the sentiment of women's clothing reviews. Specifically, we aim to:

 1. **Classify Reviews:** Develop a model to classify reviews into different rating categories (e.g., 1-5 stars or positive/negative).

 2. **Text Analysis:** Utilize natural language processing (NLP) techniques to extract meaningful features from the text reviews.

 3. **Model Evaluation:** Assess the performance of the chosen model using appropriate metrics such as accuracy, precision, recall, and F1-score.

 4. **Improve Customer Experience:** By understanding customer sentiment, provide insights to businesses to improve their products and services.


# **Data Source**

The dataset used in this project is the "Women Clothing Review" dataset.

https://github.com/YBIFoundation/MachineLearning/blob/main/Dataset/Women%20Clothing%20E-Commerce%20Review.csv

# **Import Library**

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

**Import Dataset**

In [ ]:
import os
!ls


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Women_Clothing_Review.csv to Women_Clothing_Review (1).csv


In [ ]:
import pandas as pd

# List uploaded files
for filename in uploaded.keys():
    print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

# Load the CSV file into a DataFrame
df = pd.read_csv("Women_Clothing_Review.csv")
df.head()


User uploaded file "Women_Clothing_Review (1).csv" with length 8378631 bytes


_Clothing ID  Age                    Title  \
0           767   33                      NaN   
1          1080   34                      NaN   
2          1077   60  Some major design flaws   
3          1049   50         My favorite buy!   
4           847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   _Clothing ID       23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [ ]:
df.shape

(23486, 10)

# **Missing Values**

In [ ]:
df.isna().sum()

_Clothing ID            0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df[df['Review']==""]=np.NaN

In [ ]:
df['Review'].fillna("No Review",inplace=True)

In [ ]:
df.isna().sum()

_Clothing ID            0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [ ]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# **Define Target(y) and Feature(X)**

In [ ]:
df.columns

Index(['_Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [ ]:
X=df['Review']

In [ ]:
y=df['Rating']

In [ ]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

# **Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2534)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Feature Text Conversion To Tokens**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
X_train=cv.fit_transform(X_train)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 dress', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test=cv.fit_transform(X_test)

In [ ]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years come', 'yoga pants',
       'zipper little'], dtype=object)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# **Get Model Train**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train,y_train)

MultinomialNB()

# **Get Model Prediction**

In [ ]:
y_pred=model.predict(X_test)

In [ ]:
y_pred.shape

(7046,)

# **Get Probability of Each Predicted Class**

In [ ]:
model.predict_proba(X_test)

array([[0.49618185, 0.24486463, 0.06103004, 0.04760525, 0.15031822],
       [0.78216874, 0.14994033, 0.00303086, 0.01183969, 0.05302039],
       [0.24157826, 0.03293502, 0.09784216, 0.02681906, 0.60082551],
       ...,
       [0.17435853, 0.39433537, 0.34448375, 0.04054484, 0.04627751],
       [0.19352606, 0.05163765, 0.16922826, 0.10888422, 0.4767238 ],
       [0.05104995, 0.13407208, 0.27675833, 0.1718692 , 0.36625045]])

# **Get Model Evaluation**

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print (confusion_matrix(y_test,y_pred))

[[  26   26   21   36  144]
 [  53   47   54   69  247]
 [ 126   90  109  151  385]
 [ 170  145  145  272  791]
 [ 408  279  332  690 2230]]


In [ ]:
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.03      0.10      0.05       253
           2       0.08      0.10      0.09       470
           3       0.16      0.13      0.14       861
           4       0.22      0.18      0.20      1523
           5       0.59      0.57      0.58      3939

    accuracy                           0.38      7046
   macro avg       0.22      0.21      0.21      7046
weighted avg       0.40      0.38      0.39      7046



**# Recategories Ratings as Poor (0)and Good(1)**

In [ ]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

Re_Rating as 1,2,3 as 0 and 4,5 as 1

In [ ]:
df.replace ({'Rating':{1:0,2:0,3:0,4:1,5:1}},inplace=True)


In [ ]:
y = df['Rating']

In [ ]:
X = df['Review']

# **Train Test Split**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Feature Text Conversion to Tokens**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [ ]:
X_train=cv.fit_transform(X_train)

In [ ]:
X_test = cv.fit_transform(X_test)

# **Get Model Retrain**

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train,y_train)

MultinomialNB()

# **Get Model Prediction**

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred.shape

(7046,)

In [ ]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

# **Get Model Evaulation**

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[ 449 1134]
 [ 989 4474]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.31      0.28      0.30      1583
           1       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046



# **Theory**

 ** Import necessary libraries**
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from google.colab import drive
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report  
from sklearn.metrics import confusion_matrix,classification_report

** Mount Google Drive to access the dataset**
drive.mount('/content/drive')

 **Upload the dataset file**
uploaded = files.upload()

** Load the dataset into a Pandas DataFrame **
df = pd.read_csv("Women_Clothing_Review.csv") # Assuming the uploaded file is named "Women_Clothing_Review.csv"

**Explore the dataset**
df.head()  *Display the first few rows of the DataFrame*
df.info()  *Get information about the DataFrame, including column names, data types, and non-null values*
df.shape   *Get the number of rows and columns in the DataFrame*

**Handle missing values**
df.isna().sum()  *Check for missing values in each column*
df[df['Review']==""]=np.NaN  Replace empty strings in the 'Review' column with NaN
df['Review'].fillna("No Review",inplace=True)  * Fill missing values in the 'Review' column with "No Review"*
df.isna().sum()  * Verify that there are no more missing values*

**Define target variable (y) and feature (X)**
y = df['Rating']  * Target variable is the 'Rating' column*
X = df['Review']  * Feature is the 'Review' column*

**Explore the distribution of ratings**
df['Rating'].value_counts()  * Count the occurrences of each rating value*

**Split the dataset into training and testing sets**
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y, random_state=2534)
**70% of the data is used for training, 30% for testing**
** Stratified sampling ensures that the proportion of each rating class is maintained in both sets**

** Convert text features to numerical tokens using CountVectorizer**
cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)
 **Convert text to lowercase**
 **Analyze words as features**
 **Consider 2-grams and 3-grams (combinations of 2 and 3 consecutive words)**
** Remove common English stop words**
** Limit the number of features to 5000**

X_train = cv.fit_transform(X_train)  * Fit the CountVectorizer to the training data and transform it*
cv.get_feature_names_out()  * Get the names of the extracted features*
X_train.toarray()  *Convert the sparse matrix representation to a dense array*

X_test = cv.fit_transform(X_test)  *Transform the testing data using the fitted CountVectorizer*

 **Train a Multinomial Naive Bayes model**
model = MultinomialNB()
model.fit(X_train, y_train)  * Fit the model to the training data*

 **Make predictions on the testing data**
y_pred = model.predict(X_test)
y_pred.shape  *Get the shape of the predicted values array*

** Get the probability of each predicted class**
model.predict_proba(X_test)  

**Evaluate the model performance**
print(confusion_matrix(y_test, y_pred))  * Print the confusion matrix*
print(classification_report(y_test, y_pred))  * Print the classification report*

**Recategorize ratings as Poor (0) and Good (1)**
df.replace({'Rating': {1:0, 2:0, 3:0, 4:1, 5:1}}, inplace=True)  *Ratings 1, 2, and 3 become 0, and 4 and 5 become 1*

** Update target variable (y) with the recategorized ratings**
y = df['Rating']

**Split the dataset again with the updated ratings **
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y, random_state=2529)

**Convert text features to tokens again**
X_train = cv.fit_transform(X_train)
X_test = cv.fit_transform(X_test)

** Retrain the model with the recategorized ratings**
model = MultinomialNB()
model.fit(X_train, y_train)

** Make predictions with the retrained model**
y_pred = model.predict(X_test)

** Evaluate the retrained model **
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

